config/routes.rb
require 'routes/community_domain'
require 'routes/api_request'

Kassi::Application.routes.draw do

    namespace :mercury do
      resources :images
    end

  mount Mercury::Engine => '/'

  match "/robots.txt" => RobotsGenerator

  match "/design" => "design#design"

  scope "(/:locale)" do
    scope :module => "api", :constraints => ApiRequest do
      resources :tokens, :only => :create
      resources :listings do
        resources :comments
      end
      resources :communities do
        member do
          get :classifications
        end
      end
      resources :people do
        resources :conversations do
          member do
            post :messages, :controller => :conversations, :action => "new_message"
          end
        end
        resources :devices
        resources :listings
        resources :feedbacks, :controller => :testimonials
        resources :badges
      end
      
      match 'api_version' => "api#version_check"
      match '/' => 'dashboard#api'    
    end
    
    devise_for :people, :controllers => { :confirmations => "confirmations", :registrations => "people", :omniauth_callbacks => "sessions"}, :path_names => { :sign_in => 'login'} 
    devise_scope :person do  
      get "/people/confirmation" => "confirmations#show", :as => :confirmation
      put "/people/confirmation" => "confirmations#create"
      match "/people/password/edit" => "devise/passwords#edit"
      post "/people/password" => "devise/passwords#create"
      put "/people/password" => "devise/passwords#update"
      match "/people/sign_up" => redirect("/%{locale}/login")
           
      resources :people do
        collection do
          get :check_username_availability
          get :check_email_availability
          get :check_email_availability_for_new_tribe
          get :check_email_availability_and_validity
          get :check_invitation_code
          get :not_member
          get :cancel
          get :create_facebook_based
          get :fetch_rdf_profile
        end
        member do
          put :activate
          put :deactivate
        end
        resources :listings do
          member do
            put :close
          end  
        end  
        resources :messages, :controller => :conversations do 
          collection do
            get :received
            get :sent
            get :notifications
          end
          member do
            get :accept
            get :reject
            get :confirm
            get :cancel
            put :acceptance
            put :confirmation
          end
          resources :messages
          resources :feedbacks, :controller => :testimonials do
            collection do
              put :skip
            end  
          end
          resources :payments do
            member do
              get :done
            end
            
          end
          
        end
        resource :settings do
          member do
            get :profile
            get :account
            get :notifications
            get :payments
            get :unsubscribe
          end
        end
        resources :invitations # This could be removed, but now saved for a while to keep links in old emails working
        resources :badges
        resources :testimonials
        resources :poll_answers
        resources :emails do
          member do
            post :send_confirmation
          end
        end
      end
      
      match "/signup" => "people#new", :as => :sign_up    
      match "/people/:id/:type" => "people#show", :as => :person_listings    
      
    end

    namespace :admin do
      resources :news_items
      resources :communities do
        member do
          get :edit_details
          get :edit_look_and_feel
          get :edit_welcome_email
          get :test_welcome_email
          put :mercury_update
        end
        resources :emails
      end
      resources :polls do
        collection do
          get :add_option
          get :remove_option
        end
        member do
          put :open
          put :close
        end
      end
    end
    
    resources :contact_requests
    resources :organizations
    resources :invitations
    resources :user_feedbacks, :controller => :feedbacks
    resources :homepage do
      collection do
        get :sign_in
        get :not_member
        post :join
      end
    end
    resources :tribes, :controller => :communities do
      collection do 
        get :check_domain_availability
        get :change_form_language
        post :set_organization_email
        post :confirm_organization_email
      end
    end
    resources :community_memberships, :as => :tribe_memberships
    resources :listings do
      member do
        post :follow
        delete :unfollow
      end
      collection do
        get :more_listings
        get :browse
        get :random
        get :locations_json
      end
      resources :images, :controller => :listing_images
      resources :comments
    end

    resources :infos do
      collection do
        get :about
        get :how_to_use
        get :terms
        get :privacy
        get :news
        put :mercury_update
        put :mercury_update_how_to_use
      end  
    end
    resource :terms do
      member do
        post :accept
      end  
    end    
    resources :sessions do
      collection do
        post :request_new_password
        post :change_mistyped_email
      end
    end  
    resources :consent
    resource :sms do
      get :message_arrived
    end
    resources :news_items
    resources :statistics
    resources :organizations
  end
  
  match '/:locale/api' => "dashboard#api", :as => :api
  match '/:locale/faq' => "dashboard#faq", :as => :faq
  match '/:locale/pricing' => "dashboard#pricing", :as => :pricing
  match '/:locale/dashboard_login' => "dashboard#login", :as => :dashboard_login
  match '/wdc' => 'dashboard#wdc'
  match '/okl' => 'dashboard#okl'
  match '/omakotiliitto' => 'dashboard#okl'
  match '/:locale/admin' => 'admin/news_items#index', :as => :admin
  match '/badges/:style/:id.:format' => "badges#image"
  match "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  match "/:locale/offers" => "listings#offers", :as => :offers
  match "/:locale/requests" => "listings#requests", :as => :requests
  match "/:locale/people/:person_id/messages/:conversation_type/:id" => "conversations#show", :as => :single_conversation
  match "/:locale/listings/:id/reply" => "conversations#new", :as => :reply_to_listing
  match "/:locale/listings/new/:type/:category" => "listings#new", :as => :new_request_category
  match "/:locale/listings/new/:type" => "listings#new", :as => :new_request
  match "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  match "/:locale/search" => "search#show", :as => :search
  match "/:locale/logout" => "sessions#destroy", :as => :logout, :method => :delete
  match "/:locale/signup" => "people#new", :as => :sign_up
  match "/:locale/signup/check_captcha" => "people#check_captcha", :as => :check_captcha
  match "/:locale/confirmation_pending" => "sessions#confirmation_pending", :as => :confirmation_pending
  match "/:locale/login" => "sessions#new", :as => :login
  match "/change_locale" => "i18n#change_locale", :as => :change_locale
  match '/:locale/tag_cloud' => "tag_cloud#index", :as => :tag_cloud
  match "/:locale/offers/map/" => "listings#offers_on_map", :as => :offers_on_map
  match "/:locale/requests/map/" => "listings#requests_on_map", :as => :requests_on_map
  match "/:locale/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
  match "/:locale/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
  match '/:locale/:page_type' => 'dashboard#campaign'
  
  constraints(CommunityDomain) do
    match '/:locale/' => 'homepage#index'
    match '/' => 'homepage#index'
  end  
  
  match '/:locale' => 'dashboard#index'
  
  root :to => 'dashboard#index'
  
end

app/helpers/listings_helper.rb
module ListingsHelper

  # Class is selected if conversation type is currently selected
  def get_map_tab_class(tab_name)
    current_tab_name = action_name || "map_view"
    "inbox_tab_#{current_tab_name.eql?(tab_name) ? 'selected' : 'unselected'}"
  end

  # Class is selected if listing type is currently selected
  def get_new_listing_tab_class(listing_type)
    "new_listing_form_tab_#{@listing.listing_type.eql?(listing_type) ? 'selected' : 'unselected'}"
  end

  # Class is selected if category is currently selected
  def get_type_select_icon_class(category)
    "listing_type_select_icon_#{@listing.category.name.eql?(category) ? 'selected' : 'unselected'}_#{category}"
  end

  # Removes extra characters from datetime_select field
  def clear_datetime_select(&block)
    time = "</div><div class='date_select_time_container'><div class='datetime_select_time_label'>#{t('listings.form.departure_time.at')}:</div>"
    colon = "</div><div class='date_select_time_container'><div class='datetime_select_colon_label'>:</div>"
    haml_concat capture_haml(&block).gsub(":", "#{colon}").gsub("&mdash;", "#{time}").gsub("\n", '').html_safe
  end

  # Class is selected if listing type is currently selected
  def get_listing_tab_class(tab_name)
    current_tab_name = params[:type] || "list_view"
    "inbox_tab_#{current_tab_name.eql?(tab_name) ? 'selected' : 'unselected'}"
  end

  def visibility_array
    array = []
    Listing::VALID_VISIBILITIES.each do |visibility|
      if visibility.eql?("this_community")
        array << [t(".#{visibility}", :community => @current_community.name), visibility]
      else
        array << [t(".#{visibility}"), visibility]
      end
    end
    return array
  end

  def privacy_array
    Listing::VALID_PRIVACY_OPTIONS.collect { |option| [t(".#{option}"), option] }
  end

  def listed_listing_share_type(listing)
    if listing.share_type && listing.share_type.parent
      if listing.share_type.name.eql?("offer_to_swap") || listing.share_type.name.eql?("request_to_swap")
        t("listings.show.#{listing.category.name}_#{listing.listing_type}_#{listing.share_type.name}", :default => listing.share_type.display_name.capitalize)
      else
        localized_share_type_label(listing.share_type).mb_chars.capitalize.to_s
      end
    else
      t("listings.show.#{listing.category.name}_#{listing.listing_type}", :default => listing.share_type.display_name)
    end
  end

  def listed_listing_title(listing)
    listed_listing_share_type(listing) + ": #{listing.title}"
  end

  def share_type_url(listing, map=false)
    root_path(:share_type => listing.share_type.name, :category => listing.category.name, :map => map)
  end

  # expects category to be "item", "favor", "rideshare" or "housing"
  def localized_category_label(category)
    return nil if category.nil?
    if category.class == String
      category += "s" if ["item", "favor"].include?(category)
      return t("listings.index.#{category}", :default => category.capitalize)
    else
      return category.display_name.capitalize
    end
  end

  def localized_share_type_label(share_type)
    return nil if share_type.nil?
    return share_type.display_name.capitalize
  end

  def localized_listing_type_label(listing_type_string)
    return nil if listing_type_string.nil?
    return t("listings.show.#{listing_type_string}", :default => listing_type_string.capitalize)
  end

  def listing_form_menu_title(attribute)
    # - if
    # t(".what_kind_of_category", :category => t(".#{category}_with_article", :default => t(".listing")))
  end

  def listing_form_menu_titles(community_attribute_values)
    titles = {
      "listing_type" => t(".what_do_you_want_to_do"),
      "category" => {
        "offer" => t(".what_can_you_offer"),
        "request" => t(".what_do_you_need"),
        "default" => t(".select_category")
      },
      "subcategory" => Hash[community_attribute_values["category"].collect { |category| [category, t(".what_kind_of_#{category}", :default => t(".which_subcategory"))]}],
      "share_type" => {
        "offer" => t(".how_do_you_want_to_share_it"),
        "request" => t(".how_do_you_want_to_get_it")
      }
    }
  end

  def major_currencies(hash)
    hash.inject([]) do |array, (id, attributes)|
      array ||= []
      array << [attributes[:iso_code]]
      array.sort
    end.compact.flatten
  end

  def price_as_text(listing)
    money_without_cents_and_with_symbol(listing.price).upcase +
    unless listing.quantity.blank? then " / #{listing.quantity}" else "" end +
    if @current_community.vat then " " + t("listings.displayed_price.price_excludes_vat") else "" end
  end

  def is_image_processing?(listing)
    with_first_listing_image(listing) do |first_image|
      first_image.image_processing
    end
  end

  def has_images?(listing)
    !listing.listing_images.empty?
  end

  def with_image_frame(listing, &block)
    if self.has_images?(listing) then
      first_image = listing.listing_images.first
      if first_image.image_processing then
        block.call(:image_processing, nil)
      else
        block.call(:image_ok, first_image)
      end
    elsif listing.description.blank? then
      block.call(:no_description, nil)
    end
  end

  def aspect_ratio_class(image)
    aspect_ratio = 3/2.to_f
    if image.correct_size? aspect_ratio
      "correct-ratio"
    elsif image.too_narrow? aspect_ratio
      "too-narrow"
    else
      "too-wide"
    end
  end

  def with_quantity_and_vat_text(community, listing, &block)
    buffer = []
    unless listing.quantity.blank?
      buffer.push("/ #{@listing.quantity}")
    end

    if community.vat
      buffer.push(t(".price_excludes_vat"))
    end

    block.call(buffer.join(" ")) unless buffer.empty?
  end
end

app/views/listings/_additional_listings.haml
= render :partial => "listings/listing_spacer" unless @listings.empty?
= render :partial => "listings/recent_listing", :collection => @listings, :as => :listing, :spacer_template => "listings/listing_spacer"

app/views/listings/_comment_form.haml
- if @listing.closed?
  = t(".you_cannot_send_a_new_comment_because_listing_is_closed")  
- elsif logged_in?
  .comment-form
    = form_for Comment.new, :url => listing_comments_path(:listing_id => @listing.id.to_s) do |f|
      = f.text_area :content, :class => "listing_comment_content_text_area", :placeholder => t(".ask_a_question")
      .checkbox-container
        = check_box_tag "comment[author_follow_status]", "true", :checked => true
        = label_tag "comment_author_follow_status", t(".subscribe_to_comments"), :class => "comment_checkbox_label"
      = f.hidden_field :listing_id, :value => @listing.id.to_s
      = f.hidden_field :author_id, :value => @current_user.id
      = f.hidden_field :community_id, :value => @current_community.id
      = f.button t(".send_comment"), :id => "send_comment_button"
- else
  = t(".you_must")
  = link_to t(".log_in"), login_path
  = t(".to_send_a_comment")

app/views/listings/_destination.haml
.destination
= fields_for :destination_loc do |loc|
  = loc.hidden_field :address, :value => destination_loc.address
  = loc.hidden_field :google_address, :value => destination_loc.google_address
  = loc.hidden_field :latitude, :value => destination_loc.latitude
  = loc.hidden_field :longitude, :value => destination_loc.longitude
  = loc.hidden_field :location_type, :value => destination_loc.location_type

app/views/listings/_displayed_price.haml
- if listing.price
  .icon-with-text-container
    = icon_tag("pricetag", ["icon-part"])  
    .text-part
      = money_without_cents_and_with_symbol(listing.price).upcase
      - unless listing.quantity.blank?
        = "/ #{listing.quantity}"
      - if @current_community.vat
        = t(".price_excludes_vat")

app/views/listings/_edit_links.haml
- if @listing.closed?
  = link_to t(".reopen_listing"), edit_listing_path(@listing), :class => "edit_listing"
- else   
  = link_to t(".edit_listing"), edit_listing_path(@listing), :class => "edit_listing"
  = link_to t(".close_listing"), close_person_listing_path(@current_user, @listing), :class => "close_listing", :method => :put, :remote => true

app/views/listings/_edit_profile_listing_links.haml
%div{:id => "edit-profile-listing-links-#{listing.id.to_s}", :class => "edit-profile-listing-links"}
  - if listing.closed?
    .icon-with-text-container
      %a{href: edit_listing_path(listing)}
        .ss-lock.icon-part
        .text-part= t("listings.edit_links.reopen_listing")
  - else
    .icon-with-text-container
      %a{href: edit_listing_path(listing)}
        .ss-draw.icon-part
        .text-part= t("listings.edit_links.edit_listing")
    .icon-with-text-container
      %a{href: close_person_listing_path(@current_user, listing), data: { method: "put", remote: "true"}}
        .ss-lock.icon-part
        .text-part= t("listings.edit_links.close_listing")

app/views/listings/_message_links.haml
- if @listing.closed?
  .listing-view-admin-links
    .listing-view-admin-link
      .icon-with-text-container
        = icon_tag("lock", ["icon-part"]) 
        .text-part= t("listings.reply_link.listing_closed")
    - if current_user?(@listing.author) || (@current_user && @current_user.has_admin_rights_in?(@current_community) && !@current_user.member_of?(@current_community))
      .listing-view-admin-link
        %a.action-link{href: edit_listing_path(@listing)}
          .icon-with-text-container
            = icon_tag("unlock", ["icon-part"]) 
            .text-part= t("listings.edit_links.reopen_listing")
- else    
  
  - unless current_user?(@listing.author)
    - link_path = (@listing.transaction_type.eql?("request") && @current_community.payments_in_use?) ? reply_to_listing_path(:id => @listing.id.to_s, :message_type => "free") : reply_to_listing_path(:id => @listing.id.to_s)
    - if @listing.share_type.transaction_button_text
      = link_to link_path, :class => "book-button" do
        .content
          = @listing.share_type.transaction_button_text 
    - else
      - listing_type_string = "#{@listing.category.name}_#{@listing.listing_type}#{(@listing.share_type.present? && @listing.share_type.parent) ? '_' + @listing.share_type.name : ''}"
      = link_to link_path, :class => "book-button" do
        .content
          = t("listings.link_labels.link_label_for_#{listing_type_string}", :default => t("listings.link_labels.#{Listing.opposite_share_type(@listing.transaction_type)}_this", :default => t("listings.link_labels.#{Listing.opposite_type(@listing.transaction_type)}_this")))
  
  - if current_user?(@listing.author) || (@current_user && @current_user.has_admin_rights_in?(@current_community))
    .listing-view-admin-links
      .listing-view-admin-link
        %a.icon-with-text-container{href: edit_listing_path(@listing)}
          = icon_tag("edit", ["icon-part"]) 
          .text-part= t("listings.edit_links.edit_listing")
      .listing-view-admin-link
        %a.icon-with-text-container{href: close_person_listing_path(@current_user, @listing), data: { method: "put", remote: "true"}}
          = icon_tag("lock", ["icon-part"]) 
          .text-part= t("listings.edit_links.close_listing")

app/views/listings/_must_log_in_to_create_new.haml
= t("layouts.notifications.you_must_log_in_to_create_new_listing")
= link_to("create one here", sign_up_path) + "."

app/views/listings/show.haml
- content_for :javascript do
  initialize_listing_view('#{I18n.locale}');

- content_for :extra_javascript do
  = javascript_include_tag "https://maps.google.com/maps/api/js?sensor=true"

- content_for :title_header do
  %h1
    %span#listing-title.listing-title= @listing.title

.row
  .col-8
    .row
      .col-12
        - with_image_frame(@listing) do |reason, listing_image|
          .listing-image-frame
            - if reason == :image_ok
              #listing-image-link.listing-image-frame-content
                .listing-image-vertical-centering{:class => aspect_ratio_class(listing_image) }
                  = image_tag listing_image.image.url(:big), :alt => listed_listing_title(@listing), :class => "listing-image #{aspect_ratio_class(listing_image)}"
            - else
              .listing-image-frame-content
                .listing-image-vertical-centering
                  .listing-no-image
                    - if reason == :image_processing
                      = t("listings.show.processing_uploaded_image")
                    - else
                      = t(".no_description")

    .row
      .col-12
        - if @listing.valid_until && @listing.category.name.eql?("rideshare")
          / Is there a cleaner way to create 'div' without class or id?
          %div
            .icon-with-text-container
              = icon_tag("rideshare", ["icon-part"])
              .text-part
                %strong
                  = t("listings.form.departure_time.departure_time") + ": " + l(@listing.valid_until, :format => :short)

    .row
      .col-12
        - if @listing.description && !@listing.description.blank?
          - text_with_line_breaks do
            = @listing.description

    .row
      .col-12
        - if @listing.public?
          .listing-social
            .listing-fb-like-button
              = facebook_like(current_user?(@listing.author))
            .listing-tweet-button
              = link_to("", "https://twitter.com/share", :class => "twitter-share-button", "data-count" => "horizontal", "data-via" => (@current_community.twitter_handle || "Sharetribe"))
              %script{:type => "text/javascript", :src => "https://platform.twitter.com/widgets.js"}

  %aside.col-4
    - if @listing.price
      .row
        .col-12
          .listing-price
            %span.listing-price-amount
              = money_without_cents_and_with_symbol(@listing.price).upcase
            - with_quantity_and_vat_text(@current_community, @listing) do |text|
              %span.listing-price-quantity
                = text

    .row-with-divider
      .col-12
        #listing-message-links
          = render :partial => "message_links"

    .row
      .col-12
        .listing-author
          .listing-author-avatar
            = medium_avatar_thumb(@listing.organization_or_author?(@current_community), {:class => "listing-author-avatar-image"})
          .listing-author-details
            .listing-author-name
              = link_to @listing.author.name(@current_community), @listing.author, :id => "listing-author-link", :class => "listing-author-name-link", :title => "#{@listing.author.name(@current_community)}"
            - unless current_user?(@listing.author)
              .listing-author-contact
                %a#listing-contact{href: reply_to_listing_path(:id => @listing.id.to_s, :message_type => "free"), :class => "listing-author-contact-button"}
                  .content
                    = t(".contact")

    .row-with-divider.listing-author-activity
      .col-12
        %i.listing-author-activity-icon{:class => icon_class("testimonial")}
        .listing-author-activity-item
          .listing-author-activity-value
            - if @listing.author.received_positive_testimonials.size > 0
              = @listing.author.feedback_positive_percentage.to_s + "%"
              = t("people.show.positive")
              = "(#{@listing.author.received_positive_testimonials.size}/#{@listing.author.received_testimonials.size})"
            - else
              = t(".no_reviews")
          .listing-author-activity-description
            = t(".feedback")

    - if @listing.origin_loc && @listing.origin_loc.address != ""
      .row
        .col-12
          #googlemap
            = render :partial => "googlemap", :locals => { :rideshare => (@listing.category.name == "rideshare"), :listing => @listing}
            = render :partial => "origin", :locals => { :origin_loc => @listing.origin_loc }
            - if @listing.category.name == "rideshare"
              = render :partial => "destination", :locals => { :destination_loc => @listing.destination_loc }















/ .view-item{:style => "position: absolute; top: 1000px"}

/   .item-description.section.overflow-allowed

/     #admin_edit_links
/       = render :partial => "admin_edit_links"

/     - if @listing.closed? && !current_user?(@listing.author)

/       .listing-icons
/         .icon-with-text-container
/           = icon_tag("lock", ["icon-part"])
/           .text-part= t("listings.reply_link.listing_closed")

/     - else

/       - if @listing.valid_until && @listing.category.name.eql?("rideshare")
/         .listing-departure-time
/           .icon-with-text-container
/             = icon_tag("rideshare", ["icon-part"])
/             .text-part
/               %strong
/                 = t("listings.form.departure_time.departure_time") + ": " + l(@listing.valid_until, :format => :short)

/       #listing_message_links
/         = render :partial => "message_links"

/       - unless @listing.listing_images.empty?
/         .item-image
/           - @listing.listing_images.each do |listing_image|
/             - unless listing_image.image_processing
/               %a{:href => "#", :id => "listing-image-link"}
/                 = image_tag listing_image.image.url(:medium), :alt => listed_listing_title(@listing)
/             - else
/               = t("listings.show.processing_uploaded_image")

/       - if @listing.description && !@listing.description.blank?
/         - text_with_line_breaks do
/           = @listing.description

/       .listing-icons
/         = render :partial => "displayed_price", :locals => { :listing => @listing }
/         .icon-with-text-container
/           = icon_tag("calendar", ["icon-part"])
/           .text-part
/             = t(".listing_created") + " " + time_ago(@listing.created_at)
/         .icon-with-text-container
/           = icon_tag("eye", ["icon-part"])
/           .text-part
/             = t(".times_viewed")
/             = pluralize(@listing.times_viewed.to_s, t(".time"), t(".times"))
/         - if @listing.valid_until && @listing.open? && !@listing.category.name.eql?("rideshare")
/           .icon-with-text-container
/             = icon_tag("clock", ["icon-part"])
/             .text-part
/               = t(".open_until", :date => l(@listing.valid_until, :format => :short))

/       - if @listing.public?
/         .social
/           .fb-like-container
/             = facebook_like(current_user?(@listing.author))
/           .tweet-button-container
/             = link_to("", "https://twitter.com/share", :class => "twitter-share-button", "data-count" => "horizontal", "data-via" => (@current_community.twitter_handle || "Sharetribe"))
/             %script{:type => "text/javascript", :src => "https://platform.twitter.com/widgets.js"}

/       - if @listing.has_organization_in?(@current_community)
/         .listing-author
/           .listing-author-image
/             = medium_avatar_thumb(@listing.organization_or_author?(@current_community))
/           .listing-author-description
/             %h3
/               = @listing.organization.name
/             .listing-organization-representative
/               %br/
/               .organization-representative-avatar
/                 = small_avatar_thumb(@listing.author)
/               .organization-representative-name
/                 = t(".listing_added_by")
/                 = link_to @listing.author.name(@current_community), @listing.author
/             - if @listing.author.received_testimonials.size > 0
/               .listing-author-detail-line
/                 .icon-with-text-container
/                   = icon_tag("testimonial", ["icon-part"])
/                   .text-part
/                     = t(".feedback")
/                     = @listing.author.feedback_positive_percentage.to_s + "%"
/                     = t("people.show.positive")
/                     = "(#{@listing.author.received_positive_testimonials.size}/#{@listing.author.received_testimonials.size})"
/             - unless @listing.closed? || current_user?(@listing.author)
/               .listing-author-detail-line
/                 %a{href: reply_to_listing_path(:id => @listing.id.to_s, :message_type => "free"), id: "message_listing_author_link"}
/                   .icon-with-text-container
/                     = icon_tag("mail", ["icon-part"])
/                     .text-part= t(".send_private_message")
/             - if @current_user && @current_user.member_of?(@current_community) && @listing.author.phone_number && !@listing.author.phone_number.blank? && !@listing.closed?
/               .listing-author-detail-line
/                 .icon-with-text-container
/                   = icon_tag("phone", ["icon-part"])
/                   .text-part
/                     - if @listing.author.phone_number && !@listing.author.phone_number.blank?
/                       = @listing.author.phone_number
/                     - elsif current_user?(@listing.author)
/                       = link_to t(".add_your_phone_number"), person_settings_path(:person_id => @current_user.id)
/       - else
/         .listing-author
/           .listing-author-image
/             = medium_avatar_thumb(@listing.author)
/           .listing-author-description
/             %h3
/               = link_to @listing.author.name(@current_community), @listing.author, :id => "listing_author_link"
/             - if @listing.author.received_testimonials.size > 0
/               %br/
/               .icon-with-text-container
/                 = icon_tag("testimonial", ["icon-part"])
/                 .text-part
/                   = t(".feedback")
/                   = @listing.author.feedback_positive_percentage.to_s + "%"
/                   = t("people.show.positive")
/                   = "(#{@listing.author.received_positive_testimonials.size}/#{@listing.author.received_testimonials.size})"
/             - unless @listing.closed? || current_user?(@listing.author)
/               %br/
/               %a{href: reply_to_listing_path(:id => @listing.id.to_s, :message_type => "free"), id: "message_listing_author_link"}
/                 .icon-with-text-container
/                   = icon_tag("mail", ["icon-part"])
/                   .text-part= t(".send_private_message")
/             - if @current_user && @current_user.member_of?(@current_community) && @listing.author.phone_number && !@listing.author.phone_number.blank? && !@listing.closed?
/               %br/
/               .icon-with-text-container
/                 = icon_tag("phone", ["icon-part"])
/                 .text-part
/                   - if @listing.author.phone_number && !@listing.author.phone_number.blank?
/                     = @listing.author.phone_number
/                   - elsif current_user?(@listing.author)
/                     = link_to t(".add_your_phone_number"), person_settings_path(:person_id => @current_user.id)

/   - unless @listing.closed? && !current_user?(@listing.author)
/     #comments.discussion.section.overflow-allowed
/       %h2
/         = icon_tag("chat_bubble", ["icon-with_text"])
/         .text-with-icon
/           = t(".comments")
/           %span= "(#{@listing.comments.count})"
/       #follow-links.follow-links
/         = render :partial => "follow_links"
/       #comment-list
/         = render :partial => "comment", :collection => @listing.comments
/       #comment-form
/         = render :partial => "comment_form"

/ - unless @listing.listing_images.empty?
/   #listing-image-lightbox.lightbox.image-lightbox
/     .lightbox-content.image-lightbox-content
/       %a{:href => "#", :class => "close lightbox-x", :id => "close_x"}
/         = icon_tag("cross")
/       = image_tag @listing.listing_images.first.image.url(:original)