config/routes.rb
require 'routes/community_domain'
require 'routes/api_request'

Kassi::Application.routes.draw do

    namespace :mercury do
      resources :images
    end

  mount Mercury::Engine => '/'

  match "/robots.txt" => RobotsGenerator

  match "/design" => "design#design"

  scope "(/:locale)" do
    scope :module => "api", :constraints => ApiRequest do
      resources :tokens, :only => :create
      resources :listings do
        resources :comments
      end
      resources :communities do
        member do
          get :classifications
        end
      end
      resources :people do
        resources :conversations do
          member do
            post :messages, :controller => :conversations, :action => "new_message"
          end
        end
        resources :devices
        resources :listings
        resources :feedbacks, :controller => :testimonials
        resources :badges
      end
      
      match 'api_version' => "api#version_check"
      match '/' => 'dashboard#api'    
    end
    
    devise_for :people, :controllers => { :confirmations => "confirmations", :registrations => "people", :omniauth_callbacks => "sessions"}, :path_names => { :sign_in => 'login'} 
    devise_scope :person do  
      get "/people/confirmation" => "confirmations#show", :as => :confirmation
      put "/people/confirmation" => "confirmations#create"
      match "/people/password/edit" => "devise/passwords#edit"
      post "/people/password" => "devise/passwords#create"
      put "/people/password" => "devise/passwords#update"
      match "/people/sign_up" => redirect("/%{locale}/login")
           
      resources :people do
        collection do
          get :check_username_availability
          get :check_email_availability
          get :check_email_availability_for_new_tribe
          get :check_email_availability_and_validity
          get :check_invitation_code
          get :not_member
          get :cancel
          get :create_facebook_based
          get :fetch_rdf_profile
        end
        member do
          put :activate
          put :deactivate
        end
        resources :listings do
          member do
            put :close
          end  
        end  
        resources :messages, :controller => :conversations do 
          collection do
            get :received
            get :sent
            get :notifications
          end
          member do
            get :accept
            get :reject
            get :confirm
            get :cancel
            put :acceptance
            put :confirmation
          end
          resources :messages
          resources :feedbacks, :controller => :testimonials do
            collection do
              put :skip
            end  
          end
          resources :payments do
            member do
              get :done
            end
            
          end
          
        end
        resource :settings do
          member do
            get :profile
            get :account
            get :notifications
            get :payments
            get :unsubscribe
          end
        end
        resources :invitations # This could be removed, but now saved for a while to keep links in old emails working
        resources :badges
        resources :testimonials
        resources :poll_answers
        resources :emails do
          member do
            post :send_confirmation
          end
        end
      end
      
      match "/signup" => "people#new", :as => :sign_up    
      match "/people/:id/:type" => "people#show", :as => :person_listings    
      
    end

    namespace :admin do
      resources :news_items
      resources :communities do
        member do
          get :edit_details
          get :edit_look_and_feel
          get :edit_welcome_email
          get :test_welcome_email
          put :mercury_update
        end
        resources :emails
      end
      resources :polls do
        collection do
          get :add_option
          get :remove_option
        end
        member do
          put :open
          put :close
        end
      end
    end
    
    resources :contact_requests
    resources :organizations
    resources :invitations
    resources :user_feedbacks, :controller => :feedbacks
    resources :homepage do
      collection do
        get :sign_in
        get :not_member
        post :join
      end
    end
    resources :tribes, :controller => :communities do
      collection do 
        get :check_domain_availability
        get :change_form_language
        post :set_organization_email
        post :confirm_organization_email
      end
    end
    resources :community_memberships, :as => :tribe_memberships
    resources :listings do
      member do
        post :follow
        delete :unfollow
      end
      collection do
        get :more_listings
        get :browse
        get :random
        get :locations_json
      end
      resources :images, :controller => :listing_images
      resources :comments
    end

    resources :infos do
      collection do
        get :about
        get :how_to_use
        get :terms
        get :privacy
        get :news
        put :mercury_update
        put :mercury_update_how_to_use
      end  
    end
    resource :terms do
      member do
        post :accept
      end  
    end    
    resources :sessions do
      collection do
        post :request_new_password
        post :change_mistyped_email
      end
    end  
    resources :consent
    resource :sms do
      get :message_arrived
    end
    resources :news_items
    resources :statistics
    resources :organizations
  end
  
  match '/:locale/api' => "dashboard#api", :as => :api
  match '/:locale/faq' => "dashboard#faq", :as => :faq
  match '/:locale/pricing' => "dashboard#pricing", :as => :pricing
  match '/:locale/dashboard_login' => "dashboard#login", :as => :dashboard_login
  match '/wdc' => 'dashboard#wdc'
  match '/okl' => 'dashboard#okl'
  match '/omakotiliitto' => 'dashboard#okl'
  match '/:locale/admin' => 'admin/news_items#index', :as => :admin
  match '/badges/:style/:id.:format' => "badges#image"
  match "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  match "/:locale/offers" => "listings#offers", :as => :offers
  match "/:locale/requests" => "listings#requests", :as => :requests
  match "/:locale/people/:person_id/messages/:conversation_type/:id" => "conversations#show", :as => :single_conversation
  match "/:locale/listings/:id/reply" => "conversations#new", :as => :reply_to_listing
  match "/:locale/listings/new/:type/:category" => "listings#new", :as => :new_request_category
  match "/:locale/listings/new/:type" => "listings#new", :as => :new_request
  match "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  match "/:locale/search" => "search#show", :as => :search
  match "/:locale/logout" => "sessions#destroy", :as => :logout, :method => :delete
  match "/:locale/signup" => "people#new", :as => :sign_up
  match "/:locale/signup/check_captcha" => "people#check_captcha", :as => :check_captcha
  match "/:locale/confirmation_pending" => "sessions#confirmation_pending", :as => :confirmation_pending
  match "/:locale/login" => "sessions#new", :as => :login
  match "/change_locale" => "i18n#change_locale", :as => :change_locale
  match '/:locale/tag_cloud' => "tag_cloud#index", :as => :tag_cloud
  match "/:locale/offers/map/" => "listings#offers_on_map", :as => :offers_on_map
  match "/:locale/requests/map/" => "listings#requests_on_map", :as => :requests_on_map
  match "/:locale/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
  match "/:locale/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
  match '/:locale/:page_type' => 'dashboard#campaign'
  
  constraints(CommunityDomain) do
    match '/:locale/' => 'homepage#index'
    match '/' => 'homepage#index'
  end  
  
  match '/:locale' => 'dashboard#index'
  
  root :to => 'dashboard#index'
  
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  
  has_many :options, :class_name => "PollOption"
  has_many :answers, :class_name => "PollAnswer"
  belongs_to :author, :class_name => "Person"
  
  def poll_options=(poll_options)
    options.clear
    poll_options.each { |option| options.build(option) }
  end
  
  def status
    active? ? "open" : "closed"
  end
  
  def calculate_percentages
    options.each do |option|
      option.update_attribute(:percentage, (option.answers.size.to_f / answers.size.to_f).round(3)*100)
    end
  end
  
end

app/controllers/admin/polls_controller.rb
class Admin::PollsController < ApplicationController
  
  layout "layouts/admin"
  
  before_filter :ensure_is_admin, :ensure_polls_enabled
  
  def index
    @polls = @current_community.polls.order("created_at DESC")
  end
  
  def show
    @poll = Poll.find(params[:id])
  end
  
  def new
    @poll = Poll.new
    @poll.options = [PollOption.new, PollOption.new]
    @path = admin_polls_path
    session[:option_amount] = 2
  end
  
  def edit
    @poll = Poll.find(params[:id])
    @path = admin_poll_path(@poll)
    session[:option_amount] = @poll.options.size
    render :action => :new
  end
  
  def create
    @poll = Poll.new(params[:poll])
    @current_community.active_poll.update_attribute(:active, false) if @current_community.active_poll
    if @poll.save
      flash[:notice] = "poll_created"
      redirect_to admin_polls_path(:type => "polls")
    else
      flash[:error] = "poll_creation_failed"
      render :action => :new
    end
  end
  
  def update
    @poll = Poll.find(params[:id])
    if @poll.update_attributes(params[:poll])
      flash[:notice] = "poll_updated"
      redirect_to admin_polls_path(:type => "poll")    
    else
      flash[:error] = "poll_update_failed"
      @path = admin_poll_path(:id => @poll.id.to_s)
      render :action => :new
    end
  end
  
  def destroy
    Poll.find(params[:id]).destroy
    flash[:notice] = "poll_deleted"
    redirect_to admin_polls_path(:type => "poll")
  end
  
  def add_option
    session[:option_amount] += 1
    respond_to do |format|
      format.html { redirect_to new_admin_poll_path }
      format.js { render :layout => false }
    end
  end
  
  def remove_option
    respond_to do |format|
      format.html { redirect_to new_admin_poll_path }
      format.js { render :layout => false }
    end
  end
  
  def open
    change_status(true)
  end
  
  def close
    change_status(false)
  end
  
  private
  
  def change_status(status)
    if status && @current_community.active_poll
      @previously_active_poll = @current_community.active_poll
      @previously_active_poll.update_attribute(:active, false)
    end
    @poll = Poll.find(params[:id])
    @poll.update_attribute(:active, status)
    notice = "poll_#{@poll.status}ed"
    respond_to do |format|
      format.html { 
        flash[:notice] = notice
        redirect_to admin_polls_path
      }
      format.js {
        flash.now[:notice] = notice
        render :open, :layout => false 
      }
    end
  end
  
  def ensure_polls_enabled
    redirect_to admin_news_items_path unless @current_community.polls_enabled?
  end
  
end

app/views/admin/polls/_edit_poll_links.haml
%div{:id => "poll_#{poll.id.to_s}_close_link"}
  - if poll.active?
    = link_to t(".close_poll"), close_admin_poll_path(:id => poll.id, :type => "news"), :method => :put, :remote => true
  - else
    = link_to t(".open_poll"), open_admin_poll_path(:id => poll.id, :type => "news"), :method => :put, :remote => true
  |
  = link_to t(".edit_poll"), edit_admin_poll_path(:id => poll.id, :type => "news")
  |
  = link_to t(".delete_poll"), admin_poll_path(:id => poll.id, :type => "news"), :method => :delete

app/views/admin/polls/_new_option.haml
.form_field_container{:id => "poll_option_#{index}"}
  = fields_for "poll[poll_options][]", PollOption.new do |option_form|
    = option_form.label :label, t('.option') + ":", :class => "input"
    = option_form.text_field :label, :class => "option_field", :value => (option ? option.label : "")
    .remove_option_link
      = link_to t(".remove_option"), remove_option_admin_polls_path(:option => index), :remote => true, :tabindex => "-1"

app/views/admin/polls/_poll.haml
.news_item_admin_view{:id => "poll_#{poll.id.to_s}"}
  .news_item_admin_view_header
    %span.poll_status_container{:id => "poll_#{poll.id.to_s}_status"}
      = render :partial => "poll_status", :locals => { :poll => poll }
    .poll_admin_view_title
      %h4= link_to poll.title, admin_poll_path(poll, :type => "polls")
      %span.poll_author
        = link_to poll.author.given_name_or_username, poll.author
        = l(poll.created_at, :format => :short)
    %span.poll_admin_links
      = render :partial => "edit_poll_links", :locals =>  { :poll => poll }

app/views/admin/polls/_poll_answer.haml
.poll_answer
  = answer.comment
  = link_to answer.answerer.given_name_or_username, answer.answerer
  = l(answer.created_at, :format => :short)

app/views/admin/polls/_poll_status.haml
%span{:class => "poll_status_#{poll.status}"}= t(".#{poll.status}")

app/views/admin/polls/add_option.js.erb
/* Add a new option field */
$("#options").append("<%= escape_javascript(render(:partial => 'admin/polls/new_option', :locals => {:option => PollOption.new, :index => session[:option_amount]})) %>");

app/views/admin/polls/index.haml
#news_items_admin_view_title.grid_12.alpha
  %h3= t(".polls")
.grid_6.omega
  #create_news_item_link
    = link_to t(".create_poll"), new_admin_poll_path(:type => "polls")
.clear
  
#polls_admin_view_list
  - if @polls.size > 0
    = render :partial => @polls, :spacer_template => "listings/listing_spacer"
  - else
    #no_news_found
      = t(".no_polls")

app/views/admin/polls/new.haml
- content_for :javascript do
  initialize_admin_new_poll_form();

#new_poll_form
  %h2= t(".#{controller.action_name}_poll")
  = form_for @poll, :url => @path do |form|
    .form_field_container
      = form.label :title, t('.title'), :class => "input"
      = form.text_field :title, :class => "text_field", :maxlength => "200"
    #options
      - @poll.options.each_with_index do |option, index|
        = render :partial => "new_option", :locals => { :option => option, :index => index }
    .option_link_container
      = link_to "+ " + t(".add_option"), add_option_admin_polls_path, :remote => true
    .new_listing_form_field_container
      = form.hidden_field(:author_id, :value => @current_user.id)
      = form.hidden_field(:community_id, :value => @current_community.id)
      = form.submit t(".save_poll"), :class => "send_button"

app/views/admin/polls/open.js.erb
/* Update the status of the poll that was opened / closed  */
$("#poll_<%= @poll.id.to_s %>_status").html("<%= escape_javascript(render(:partial => 'admin/polls/poll_status', :locals => {:poll => @poll })) %>");

/* Update the status link of the poll that was opened / closed  */
$("#poll_<%= @poll.id.to_s %>_close_link").html("<%= escape_javascript(render(:partial => 'admin/polls/edit_poll_links', :locals => {:poll => @poll })) %>");

<% if @previously_active_poll %>
  
  /* Update the status of another poll that was closed if that is the case  */
  $("#poll_<%= @previously_active_poll.id.to_s %>_status").html("<%= escape_javascript(render(:partial => 'admin/polls/poll_status', :locals => {:poll => @previously_active_poll })) %>");

  /* Update the status link of the poll that was opened / closed  */
  $("#poll_<%= @previously_active_poll.id.to_s %>_close_link").html("<%= escape_javascript(render(:partial => 'admin/polls/edit_poll_links', :locals => {:poll => @previously_active_poll })) %>");

<% end %>

app/views/admin/polls/remove_option.js.erb
/* Remove the selected option field */
$("#poll_option_<%= escape_javascript(params[:option]) %>").remove();

app/views/admin/polls/show.haml
.grid_18
  #news_items_admin_view_title.grid_12.alpha
    %h3= @poll.title
  .grid_6.omega
    #create_news_item_link
      = link_to t(".edit_poll"), edit_admin_poll_path(@poll, :type => "polls")
  .clear
  
.grid_18
  #polls_admin_view_list
    #polls_admin_view_answer_percentages
      - @poll.options.each_with_index do |option, index|
        .option_result
          %span.option_title
            = "#{(index + 1)}."
            = option.label
          %span.option_percentage_admin_view
            = "#{option.percentage}%"
            = "(#{pluralize(option.answers.size.to_s, t('homepage.poll_form.poll_answer'), t('homepage.poll_form.poll_answers'))})"

  
    - if @poll.answers.size > 0
      = render :partial => "poll_answer", :collection => @poll.answers, :as => :answer, :spacer_template => "listings/listing_spacer"
    - else
      #no_news_found
        = t(".no_polls")