config/routes.rb
require 'routes/community_domain'
require 'routes/api_request'

Kassi::Application.routes.draw do

    namespace :mercury do
      resources :images
    end

  mount Mercury::Engine => '/'

  match "/robots.txt" => RobotsGenerator

  match "/design" => "design#design"

  scope "(/:locale)" do
    scope :module => "api", :constraints => ApiRequest do
      resources :tokens, :only => :create
      resources :listings do
        resources :comments
      end
      resources :communities do
        member do
          get :classifications
        end
      end
      resources :people do
        resources :conversations do
          member do
            post :messages, :controller => :conversations, :action => "new_message"
          end
        end
        resources :devices
        resources :listings
        resources :feedbacks, :controller => :testimonials
        resources :badges
      end
      
      match 'api_version' => "api#version_check"
      match '/' => 'dashboard#api'    
    end
    
    devise_for :people, :controllers => { :confirmations => "confirmations", :registrations => "people", :omniauth_callbacks => "sessions"}, :path_names => { :sign_in => 'login'} 
    devise_scope :person do  
      get "/people/confirmation" => "confirmations#show", :as => :confirmation
      put "/people/confirmation" => "confirmations#create"
      match "/people/password/edit" => "devise/passwords#edit"
      post "/people/password" => "devise/passwords#create"
      put "/people/password" => "devise/passwords#update"
      match "/people/sign_up" => redirect("/%{locale}/login")
           
      resources :people do
        collection do
          get :check_username_availability
          get :check_email_availability
          get :check_email_availability_for_new_tribe
          get :check_email_availability_and_validity
          get :check_invitation_code
          get :not_member
          get :cancel
          get :create_facebook_based
          get :fetch_rdf_profile
        end
        member do
          put :activate
          put :deactivate
        end
        resources :listings do
          member do
            put :close
          end  
        end  
        resources :messages, :controller => :conversations do 
          collection do
            get :received
            get :sent
            get :notifications
          end
          member do
            get :accept
            get :reject
            get :confirm
            get :cancel
            put :acceptance
            put :confirmation
          end
          resources :messages
          resources :feedbacks, :controller => :testimonials do
            collection do
              put :skip
            end  
          end
          resources :payments do
            member do
              get :done
            end
            
          end
          
        end
        resource :settings do
          member do
            get :profile
            get :account
            get :notifications
            get :payments
            get :unsubscribe
          end
        end
        resources :invitations # This could be removed, but now saved for a while to keep links in old emails working
        resources :badges
        resources :testimonials
        resources :poll_answers
        resources :emails do
          member do
            post :send_confirmation
          end
        end
      end
      
      match "/signup" => "people#new", :as => :sign_up    
      match "/people/:id/:type" => "people#show", :as => :person_listings    
      
    end

    namespace :admin do
      resources :news_items
      resources :communities do
        member do
          get :edit_details
          get :edit_look_and_feel
          get :edit_welcome_email
          get :test_welcome_email
          put :mercury_update
        end
        resources :emails
      end
      resources :polls do
        collection do
          get :add_option
          get :remove_option
        end
        member do
          put :open
          put :close
        end
      end
    end
    
    resources :contact_requests
    resources :organizations
    resources :invitations
    resources :user_feedbacks, :controller => :feedbacks
    resources :homepage do
      collection do
        get :sign_in
        get :not_member
        post :join
      end
    end
    resources :tribes, :controller => :communities do
      collection do 
        get :check_domain_availability
        get :change_form_language
        post :set_organization_email
        post :confirm_organization_email
      end
    end
    resources :community_memberships, :as => :tribe_memberships
    resources :listings do
      member do
        post :follow
        delete :unfollow
      end
      collection do
        get :more_listings
        get :browse
        get :random
        get :locations_json
      end
      resources :images, :controller => :listing_images
      resources :comments
    end

    resources :infos do
      collection do
        get :about
        get :how_to_use
        get :terms
        get :privacy
        get :news
        put :mercury_update
        put :mercury_update_how_to_use
      end  
    end
    resource :terms do
      member do
        post :accept
      end  
    end    
    resources :sessions do
      collection do
        post :request_new_password
        post :change_mistyped_email
      end
    end  
    resources :consent
    resource :sms do
      get :message_arrived
    end
    resources :news_items
    resources :statistics
    resources :organizations
  end
  
  match '/:locale/api' => "dashboard#api", :as => :api
  match '/:locale/faq' => "dashboard#faq", :as => :faq
  match '/:locale/pricing' => "dashboard#pricing", :as => :pricing
  match '/:locale/dashboard_login' => "dashboard#login", :as => :dashboard_login
  match '/wdc' => 'dashboard#wdc'
  match '/okl' => 'dashboard#okl'
  match '/omakotiliitto' => 'dashboard#okl'
  match '/:locale/admin' => 'admin/news_items#index', :as => :admin
  match '/badges/:style/:id.:format' => "badges#image"
  match "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  match "/:locale/offers" => "listings#offers", :as => :offers
  match "/:locale/requests" => "listings#requests", :as => :requests
  match "/:locale/people/:person_id/messages/:conversation_type/:id" => "conversations#show", :as => :single_conversation
  match "/:locale/listings/:id/reply" => "conversations#new", :as => :reply_to_listing
  match "/:locale/listings/new/:type/:category" => "listings#new", :as => :new_request_category
  match "/:locale/listings/new/:type" => "listings#new", :as => :new_request
  match "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  match "/:locale/search" => "search#show", :as => :search
  match "/:locale/logout" => "sessions#destroy", :as => :logout, :method => :delete
  match "/:locale/signup" => "people#new", :as => :sign_up
  match "/:locale/signup/check_captcha" => "people#check_captcha", :as => :check_captcha
  match "/:locale/confirmation_pending" => "sessions#confirmation_pending", :as => :confirmation_pending
  match "/:locale/login" => "sessions#new", :as => :login
  match "/change_locale" => "i18n#change_locale", :as => :change_locale
  match '/:locale/tag_cloud' => "tag_cloud#index", :as => :tag_cloud
  match "/:locale/offers/map/" => "listings#offers_on_map", :as => :offers_on_map
  match "/:locale/requests/map/" => "listings#requests_on_map", :as => :requests_on_map
  match "/:locale/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
  match "/:locale/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
  match '/:locale/:page_type' => 'dashboard#campaign'
  
  constraints(CommunityDomain) do
    match '/:locale/' => 'homepage#index'
    match '/' => 'homepage#index'
  end  
  
  match '/:locale' => 'dashboard#index'
  
  root :to => 'dashboard#index'
  
end

app/controllers/api/conversations_controller.rb
class Api::ConversationsController < Api::ApiController
  include ConversationsHelper
  
  before_filter :authenticate_person!
  before_filter :find_conversation, :except => [:index, :create]
  before_filter :only => :create do |controller|
    controller.ensure_authorized_to_view_listing(true)
  end
  before_filter :person_authorized_to_view_conversation, :except => [:index, :create]
  before_filter :ensure_listing_author_is_not_current_user, :only => :create
  
  def index
    @conversations = current_person.conversations.order("last_message_at DESC").paginate(:per_page => @per_page, :page => @page)
  end
  
  def show
    respond_with @conversation
  end
  
  def create    
    @conversation = Conversation.new(params.slice("listing_id","status", "title").merge({
                                        "message_attributes" => {
                                            "content" => params["content"],
                                            "sender_id" => params["person_id"]},
                                        "conversation_participants" => {
                                            params["person_id"] => true,
                                            params["target_person_id"] => true
                                        } 
                                      }))
    # If related to listing, check that it's open and the user is authorized to view it
    if @listing
      if @listing.closed?
        response.status = 403
        render :json => ["Cannot reply to listing that is not open."] and return
      end
      unless @listing.visible_to?(@current_user, @current_community)
        response.status = 403
        render :json => ["Cannot reply to listing that should not be visible to current user."] and return
      end
    end
    
    if @conversation.title.nil?
      if @conversation.listing_id
        # set title automatically if not given
        @conversation.title = get_message_title(Listing.find(@conversation.listing_id))
      else 
        response.status = 404
        render :json => ["If no listing_id is given, title is obligatory parameter."] and return
      end
    end

    
    if @conversation.save
      response.status = 201
      Delayed::Job.enqueue(MessageSentJob.new(@conversation.messages.last.id, @current_community.id))
      respond_with @conversation
    else
      response.status = 400
      render :json => @conversation.errors.full_messages and return
    end
    
  end
  
  def update
    status = params["status"]
    if Conversation::VALID_STATUSES.include?(status) && @conversation.update_attributes(:status => status)
      if status == "accepted" || status == "rejected"
        @conversation.accept_or_reject(@current_user, @current_community, false)
      elsif status == "confirmed" || status == "canceled"
        @conversation.confirm_or_cancel(current_user, current_community, false)
      else
        raise "API conversation#update called with status that is not yet supported"
      end
      respond_with @conversation
    else
      response.status = 400
      render :json => ["The conversation status (#{status}) is not valid."] and return
    end
  end
  
  def new_message
    @message = Message.new(:content => params["content"], :sender_id => current_person.id, :conversation => @conversation)
    
    if @message.save 
      response.status = 201
      @message.conversation.send_email_to_participants(@current_community)
      respond_with @conversation
    else
       response.status = 400
       render :json => @message.errors.full_messages and return
    end  
    
    
  end
  
  def find_conversation
    @conversation = Conversation.find_by_id(params[:id])
    
    if @conversation.nil?
      response.status = 404
      render :json => ["No conversation found with given ID"] and return
    end
  end
  
  def person_authorized_to_view_conversation
    unless @conversation.participants.include?(@current_user)
      response.status = 403
      render :json => ["The logged in user is not part of this conversation."] and return
    end
  end
  
  def ensure_listing_author_is_not_current_user
    if (params["target_person_id"] && current_user?(Person.find_by_id(params["target_person_id"]))) || (!params["listing_id"] && listing = Listing.find_by_id(params["listing_id"])  && current_user?(listing.author))
      response.status = 400
      render :json => ["You cannot send message to yourself."] and return
    end
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  
  def get_message_title(listing)
    listing.title
  end
  
  def transaction_proposal_form_title(listing)
    if ["item", "favor", "housing", "rideshare"].include?(listing.category.top_level_parent.name)
      "#{listing.category.top_level_parent.name}_#{listing.listing_type}#{listing.share_type.present? ? '_' + listing.share_type.name : ''}_message_form_title"
    else
      "item_#{listing.listing_type}_#{listing.share_type.name}_message_form_title"
    end
  end
  
  def icon_for(status)
    case status
    when "accepted"
      "ss-check"
    when "confirmed"
      "ss-check"
    when "rejected"
      "ss-delete"
    when "canceled"  
      "ss-delete"
    when "paid"
      "ss-check"
    end
  end
  
  def path_for_status_link(status, conversation, current_user)
    case status
    when "accept"
      accept_person_message_path(:person_id => current_user.id, :id => conversation.id.to_s)
    when "confirm"
      confirm_person_message_path(:person_id => current_user.id, :id => conversation.id.to_s)
    when "reject"
      reject_person_message_path(:person_id => @current_user.id, :id => conversation.id.to_s)
    when "cancel"  
      cancel_person_message_path(:person_id => current_user.id, :id => conversation.id.to_s)
    end 
  end
  
end

app/views/conversations/_additional_messages.haml
= render :partial => "conversation", :collection => @conversations, :as => :conversation

app/views/conversations/_additional_notifications.haml
= render :partial => "inbox_spacer" unless @notifications.empty?
= render :partial => "notification", :collection => @notifications, :as => :notification, :spacer_template => "inbox_spacer"

app/views/conversations/_conversation.haml
- other_party = conversation.other_party(@current_user)
- unless other_party.nil?
  - last_message = conversation.last_message
  .feed-item.inbox-feed-item{:class => (conversation.read_by?(@current_user) ? "" : "unread"), :id => "conversation_#{conversation.id.to_s}"}
    .feed-author-avatar
      = small_avatar_thumb other_party
    .feed-content
      .author
        = render :partial => "conversation_with", :locals => { :conversation => conversation, :other_party => other_party }
        = t("conversations.show.last_message_at", :time => time_ago(conversation.last_message_at))
      %h2= link_to conversation.title, single_conversation_path(:conversation_type => action_name, :id => conversation.id), :id => "conversation_title_link_#{conversation.id.to_s}"
      %small.feed-excerpt
        - if last_message.sender.eql?(@current_user)
          .ss-reply.conversation-icon
          - if last_message.content.blank?
            - if last_message.action.eql?("pay")
              .conversation-text= t("conversations.message.paid", :sum => humanized_money_with_symbol(last_message.conversation.payment.total_sum))
            - else
              .conversation-text= t(".#{last_message.action}ed_#{last_message.conversation.discussion_type}").capitalize
          - else
            .conversation-text= link_to("\"#{truncate(last_message.content, :length => 100, :omission => "...")}\"", single_conversation_path(:conversation_type => action_name, :id => conversation.id))
        - else
          - if last_message.content.blank?
            - if last_message.action.eql?("pay")
              = t("conversations.message.paid", :sum => humanized_money_with_symbol(last_message.conversation.payment.total_sum))
            - else
              = t(".#{last_message.action}ed_#{last_message.conversation.discussion_type}").capitalize
          - else
            = link_to("\"#{truncate(last_message.content, :length => 100, :omission => "...")}\"", single_conversation_path(:conversation_type => action_name, :id => conversation.id))
      - unless conversation.status.eql?("free")
        %small
          .listed-conversation-status-padding{:id => "conversation_#{conversation.id.to_s}_status"}
            = render :partial => "status", :locals => { :conversation => conversation }
      

app/views/conversations/_conversation_with.haml
- if conversation.listing
  - if conversation.status.eql?("free")
    = t("conversations.show.conversation_about_listing", :person => link_to(other_party.name, other_party), :listing => link_to(conversation.listing.title, conversation.listing)).html_safe
  - else
    - if current_user?(conversation.messages.first.sender)
      = t("conversations.show.message_sent_to")
      = link_to other_party.name, other_party
    - else
      = t("conversations.show.message_sent_by")
      = link_to(other_party.name, other_party)
    = t("conversations.show.in_response_to_listing")
    = link_to(conversation.listing.title, conversation.listing)
- else
  = t("conversations.show.conversation_with_user", :person => link_to(other_party.name, other_party)).html_safe

app/views/conversations/_inbox_spacer.haml
.inbox_spacer

app/views/conversations/_message.haml
.message{:id => "message#{message.id.to_s}"}
  .avatar
    = small_avatar_thumb(message.sender)
  %h3
    = link_to message.sender.name(@current_community), message.sender
  - if message.action
    - if message.action.eql?("pay")
      %b= t(".paid", :sum => humanized_money_with_symbol(message.conversation.payment.total_sum))
    - else
      %b= t(".#{message.action}ed_#{message.conversation.discussion_type}")
  %small= time_ago(message.created_at)
  .message-content
    - text_with_line_breaks do  
      = message.content

app/views/conversations/_notification.haml
- if notification.notifiable.present?
  .notification{:class => (@unread_notifications.include?(notification) ? "unread" : "")}
    = render :partial => "conversations/notifications/#{notification.notifiable_type.downcase}#{notification.description? ? '_' + notification.description + '_' : '' }notification", :locals => { :notification => notification }
- else
  - # This is definitely not the best place to clean up broken notifications, but there's also no point in crawling them separately
  - # so if the notifiable object is gone, destory this notification
  - notification.destroy

app/views/conversations/_status_link.haml
.inbox-horizontally-aligned-link
  %a{:href => path_for_status_link(status, conversation, @current_user), :class => "status-link #{status}"}
    .content
      .icon-with-text{:class => icon_for("#{status}ed")}
      .text-with-icon
        - if ["accept", "reject"].include?(status)
          = t(".#{status}_#{conversation.discussion_type}")
        - else
          = t(".#{status}")

app/views/conversations/accept.haml
- content_for :javascript do
  initialize_accept_transaction_form(#{@current_community.commission_percentage || "null"}, #{APP_CONFIG.service_fee_tax_percentage || "0"});

- content_for :title_header do
  %h1= t("layouts.no_tribe.inbox")

.centered-section-wide.conversation-status-form
  %h2= t(".respond_to_#{@conversation.discussion_type}")
  = form_for @conversation, :url => acceptance_person_message_path(:person_id => @current_user.id, :id => @conversation.id), :html => { :method => "put" } do |form|
    
    .conversation-action
      - ["accept", "reject"].each do |action| 
        %label{:for => "action-#{action}", :class => "radio hidden"}
          = radio_button_tag "conversation[status]", action, @action.eql?(action), :id => "action-#{action}"
        %a.conversation-action.hidden{:id => "#{action}", :name => "#{action}-link", :class => (@action.eql?(action) ? action : "")}
          .link-icon{:class => icon_for("#{action}ed")}
          .link-text{:id => "#{action}-action-link"}= t(".#{action}_#{@conversation.discussion_type}")
    
    - if @payout_registration_missing
      .hidden-accept-form.visible-when-accept{:class => (@action.eql?("accept") ? "" : "hidden")}
        %br
        %p#conversation-payment-details-missing
          = t(".you_need_to_fill_payout_details_before_accepting", :payment_settings_link => link_to(t(".payment_settings_link"), payments_person_settings_path, :id => "#conversation-payment-settings-link")).html_safe
    
    %div{:class => (@payout_registration_missing ? "hidden-accept-form visible-when-reject #{@action.eql?("accept") ? "hidden" : ""}" : "")}
      - if @current_community.payment_possible_for?(@conversation.listing)
        = render :partial => @current_community.payment_gateways.first.form_template_dir + "/form"

      = fields_for "conversation[message_attributes]", Message.new do |message_form|
        = message_form.label :content, t("conversations.new.message"), :class => "input"
        = message_form.text_area :content, :class => "text_area", :placeholder => t(".optional_message")
        = message_form.hidden_field :sender_id, :value => @current_user.id
        = message_form.hidden_field :action, :value => @action
    
      - if @conversation.listing.open?
        .close-listing-radio-buttons

          .checkbox-container
            = radio_button_tag "close_listing", true, true, :id => "do_close_listing"
            = label_tag "do_close_listing", t(".close_listing", :listing_title_link => link_to(@conversation.listing.title, @conversation.listing)).html_safe, :class => "radio"

          .checkbox-container
            = radio_button_tag "close_listing", false, false, :id => "do_not_close_listing"
            = label_tag "do_not_close_listing", t(".update_later"), :class => "radio"
    
      = form.hidden_field :status, :value => "#{@action}ed"
      = form.button t("conversations.new.send"), :class => "send_button", :id => "send_testimonial_button"

app/views/conversations/confirm.haml
- content_for :javascript do
  initialize_confirm_transaction_form();

- content_for :title_header do
  %h1= t("layouts.no_tribe.inbox")

.centered-section.conversation-status-form
  = form_for @conversation, :url => confirmation_person_message_path(:person_id => @current_user.id, :id => @conversation.id), :html => { :method => "put" } do |form|
    
    - if @conversation.can_be_confirmed?(@current_community)
    
      .conversation-action
        - ["confirm", "cancel"].each do |action| 
          %label{:for => "action-#{action}", :class => "radio hidden"}
            = radio_button_tag "conversation[status]", action, @action.eql?(action), :id => "action-#{action}"
          %a.conversation-action.hidden{:id => "#{action}", :name => "#{action}-link", :class => (@action.eql?(action) ? action : "")}
            .link-icon{:class => icon_for("#{action}ed")}
            .link-text{:id => "#{action}-action-link"}= t(".#{action}")

      .conversation-action-description
        - ["confirm", "cancel"].each do |action|
          %div{:class => "#{action}-description #{@action.eql?(action) ? '' : 'hidden'}"}
            = t(".#{action}_description")
      
      = fields_for "conversation[message_attributes]", Message.new do |message_form|
        = message_form.hidden_field :sender_id, :value => @current_user.id
        = message_form.hidden_field :action, :value => @action
      
      = form.hidden_field :status, :value => "#{@action}ed"
            
    - else
    
      %h2= t(".canceling_payed_transaction")
    
      .conversation-action-description
        = t(".cancel_payed_description")
    
      = fields_for "conversation[message_attributes]", Message.new do |message_form|
        = message_form.label :content, t("conversations.new.message"), :class => "input"
        = message_form.text_area :content, :class => "text_area", :placeholder => t("conversations.accept.optional_message")
        = message_form.hidden_field :sender_id, :value => @current_user.id
        = message_form.hidden_field :action, :value => "cancel"
    
      = form.hidden_field :status, :value => "canceled"
    
    - if @current_community.testimonials_in_use
      .close-listing-radio-buttons
    
        .checkbox-container
          = radio_button_tag "give_feedback", true, true, :id => "do_give_feedback"
          = label_tag "do_give_feedback", t(".give_feedback_to", :person_link => link_to(@conversation.other_party(@current_user).name, @conversation.other_party(@current_user))).html_safe, :class => "radio"

        .checkbox-container
          = radio_button_tag "give_feedback", false, false, :id => "do_not_give_feedback"
          = label_tag "do_not_give_feedback", t(".do_not_give_feedback"), :class => "radio"
    
    
    
    = form.button t(".continue"), :class => "send_button", :id => "send_testimonial_button"

app/views/conversations/index.haml
= render :partial => "layouts/left_hand_navigation", :locals => { :links => inbox_links_for(@current_user) }

- content_for :title_header do
  %h1= t("layouts.no_tribe.inbox")

#conversations.inbox-feed.left-navi-section
  - if @conversations && !@conversations.empty?
    = render :partial => @conversations
    = will_paginate(@conversations)
    = pageless(@conversations.total_pages, '#conversations', "#{action_name}", t('.loading_more_messages'))    
  - else
    #no_conversations
      = t(".no_#{action_name}_messages")
  

app/views/conversations/new.haml
- content_for :javascript do
  initialize_send_message_form('#{I18n.locale}', '#{params[:message_type] ? params[:message_type] : Listing.opposite_type(@listing.transaction_type)}');

#new_message_form.centered-section
  - if params[:message_type]
    %h2= t(".send_message_to_user", :person => @target_person.given_name_or_username)
  - elsif @listing.share_type.transaction_button_text
    %h2
      = @listing.share_type.transaction_button_text
      = link_to(@listing.title, @listing)
  - else
    %h2= t(".#{transaction_proposal_form_title(@listing)}", :listing => link_to(@listing.title, @listing), :person => author_link(@listing), :default => t(".#{Listing.opposite_type(@listing.transaction_type)}_message_form_title", :listing => link_to(@listing.title, @listing), :person => author_link(@listing)).html_safe).html_safe   
  %p
    = t(".this_message_is_private", :person => @target_person.given_name_or_username)
    - if params[:message_type]
      = t(".you_will_get_notified", :person => @target_person.given_name_or_username)
    - else
      = t(".you_will_get_notified_of_acceptance", :person => @target_person.given_name_or_username)
  = form_for @conversation, :url => person_messages_path(:person_id => @current_user.id) do |form|
    = form.label :title, t('.title')
    = form.text_field :title, :class => "text_field", :maxlength => "120", :value => (params[:message_type] ? "" : get_message_title(@listing))
      
    = fields_for "conversation[message_attributes]", Message.new do |message_form|
      = message_form.label :content, t('.message')
      = message_form.text_area :content, :class => "text_area"
      = message_form.hidden_field :sender_id, :value => @current_user.id
      
    = hidden_field_tag "conversation[conversation_participants][#{@current_user.id}]", true
    = hidden_field_tag "conversation[conversation_participants][#{@target_person.id}]", false
    - if @listing
      = form.hidden_field :listing_id, :value => @listing.id
    - if params[:message_type]
      = form.hidden_field :status, :value => params[:message_type]
    - if params[:profile_message]
      = hidden_field_tag "profile_message", params[:profile_message]
      = hidden_field_tag "target_person_id", @target_person.id
    - if params[:comment_message]
      = hidden_field_tag "comment_message", params[:comment_message]
      = hidden_field_tag :listing_id, @listing.id
      = hidden_field_tag "target_person_id", @target_person.id
    = form.hidden_field :community_id, :value => @current_community.id
    = form.button t(".send_message"), :class => "send_button"

  

app/views/conversations/notifications.haml
= render :partial => "layouts/left_hand_navigation", :locals => { :links => inbox_links_for(@current_user) }

- content_for :title_header do
  %h1= t("layouts.conversations.notifications")

#conversations.inbox-notifications.left-navi-section
  - if @notifications.empty?
    = t(".no_notifications")
  - else
    = render :partial => "notification", :collection => @notifications, :as => :notification, :spacer_template => "inbox_spacer"
    = will_paginate(@notifications)
    = pageless(@notifications.total_pages, '#conversations', "#{action_name}", t('.loading_more_notifications'))
  

app/views/conversations/show.haml
- content_for :javascript do
  initialize_reply_form('#{I18n.locale}');

= render :partial => "layouts/left_hand_navigation", :locals => { :links => inbox_links_for(@current_user) }

- content_for :title_header do
  %h1= t("layouts.no_tribe.inbox")

.left-navi-section.conversation
  %h2= @conversation.title
  .avatar-container
    .avatar
      = small_avatar_thumb @other_party
    .avatar-text
      = render :partial => "conversation_with", :locals => { :conversation => @conversation, :other_party => @other_party }  

  #messages
    = render :partial => "message", :collection => @conversation.messages
  
  - if @conversation.listing && !@conversation.status.eql?("free")
    .conversation-status-lower
      .conversation-status-container{:id => "conversation_#{@conversation.id.to_s}_status"}
        = render :partial => "status", :locals => { :conversation => @conversation }
  
  #reply_form
    = form_for Message.new, :url => person_message_messages_path(:person_id => @current_user.id, :message_id => @conversation.id.to_s) do |f|
      = f.label :content, t(".write_a_reply")
      = f.text_area :content, :class => "reply_form_text_area"
      = f.hidden_field :conversation_id, :value => @conversation.id.to_s
      = f.hidden_field :sender_id, :value => @current_user.id
      = f.button t(".send_reply")